%\documentclass[a4paper,10pt]{article}
\documentclass[a4paper,11pt]{book}
\usepackage{C:/WRK/Micro3/TeX/Micro3}
%\usepackage{pscyr}
%\usepackage{cm-super}
%\usepackage[cp1251]{inputenc}
%\usepackage[english,russian]{babel}
%\usepackage{color}
%\pdfoutput=0 % uncomment this if running PDFTeX in TeX mode
%\usepackage{ifpdf}
%\ifx\pdftexversion\undefined %if using TeX
%  \usepackage{graphicx}
%\else %if using PDFTeX
%  \usepackage[pdftex]{graphicx}
%\fi
%\ifpdf %if using PDFTeX in PDF mode
%  \DeclareGraphicsExtensions{.pdf,.png,.mps}
%  \usepackage{pgf}
%\else %if using TeX or PDFTeX in TeX mode
%  \usepackage{graphicx}
%  \DeclareGraphicsExtensions{.eps,.bmp}
%  \DeclareGraphicsRule{.emf}{bmp}{}{}% declare EMF filename extension
%  \DeclareGraphicsRule{.png}{bmp}{}{}% declare PNG filename extension
%  \usepackage{pgf}
%  \usepackage{pstricks}%variant: \usepackage{pst-all}
%\fi
\usepackage{epic,bez123}
%\usepackage{floatflt}% package for floatingfigure environment
%\usepackage{wrapfig}% package for wrapfigure environment
%\renewcommand*{\rmdefault}{ftm} 
%\renewcommand*{\sfdefault}{ftx} 
%\renewcommand*{\ttdefault}{fcr} 

%\def\acdefault{fac} %% Academy
%\def\aqdefault{faq} %% AntiquaPSCyr
%\def\codefault{fco} %% College
%\def\hadefault{fha} %% HandbookPSCyr
%\def\jndefault{fjn} %% JournalPSCyr
%\def\lzdefault{flz} %% Lazurski
%\def\tmdefault{ftm} %% TimesNewRomanPSMT

%\def\ardefault{far} %% ArialMT
%\def\madefault{fma} %% MagazinePSCyr
%\def\txdefault{ftx} %% TextbookPSCyr

%\def\erdefault{fer} %% ERKurierPSCyr
%\def\crdefault{fcr} %% CourierNewPSMT

%\usepackage[active,dvips]{preview}%psfixbb,